# Следующие две команды выполняются после включения режима NumLock
# После их завершения желательно вернуть NumLock в неактивное положение.

KEY_KP6+KEY_NUMLOCK   1    /usr/bin/mpc next
KEY_KP4+KEY_NUMLOCK   1    /usr/bin/mpc prev

KEY_KPMINUS           1 /usr/bin/mpc volume -5
KEY_KPPLUS            1 /usr/bin/mpc volume +5
KEY_TAB               1 /usr/bin/mpc toggle

KEY_KP0               1 /usr/local/bin/playlist 0
KEY_KP1               1 /usr/local/bin/playlist 1
KEY_KP2               1 /usr/local/bin/playlist 2
KEY_KP3               1 /usr/local/bin/playlist 3
KEY_KP4               1 /usr/local/bin/playlist 4
KEY_KP5               1 /usr/local/bin/playlist 5
KEY_KP6               1 /usr/local/bin/playlist 6
KEY_KP7               1 /usr/local/bin/playlist 7
KEY_KP8               1 /usr/local/bin/playlist 8
KEY_KP9               1 /usr/local/bin/playlist 9
KEY_KPENTER           1 /usr/local/bin/playlist

# Эти команды выполняются с sudo, поэтому нужно добавить в конфигурацию sudoers строчку
# nobody ALL=(root) NOPASSWD: /sbin/poweroff, /usr/sbin/service play-random restart, /usr/local/bin/play-random

KEY_HOMEPAGE          1 /usr/bin/sudo /usr/sbin/service play-random restart
KEY_CALC              1 /usr/bin/sudo /usr/local/bin/play-random force 
KEY_KPDOT             1 /usr/bin/sudo /sbin/poweroff

